const types = {
	SIGNUP: 'SIGNUP',
	LOGIN: 'LOGIN',
	VERIFY_TOKEN: 'VERIFY_TOKEN',
	CREATE_BARBER: 'CREATE_BARBER',
	EDIT_BARBER: 'EDIT_BARBER',
	GET_BARBER: 'GET_BARBER',
	LOGOUT: 'LOGOUT',
	GET_BARBER_LIST: 'GET_BARBER_LIST',
	GET_BARBER_BY_ID: 'GET_BARBER_BY_ID',
	CREATE_RESERVATION: 'CREATE_RESERVATION'
};

export default types;
